keboola_o_auth_get_credentials:
    path: /credentials/{componentId}/{id}
    defaults: { _controller: KeboolaOAuthV2Bundle:Credentials:get }
    methods: [GET, POST]

keboola_o_auth_delete_credentials:
    path: /credentials/{componentId}/{id}
    defaults: { _controller: KeboolaOAuthV2Bundle:Credentials:delete }
    methods: [DELETE]

keboola_o_auth_list_credentials:
    path: /credentials/{componentId}
    defaults: { _controller: KeboolaOAuthV2Bundle:Credentials:list }
    methods: [GET]

keboola_o_auth_add_credentials:
    path: /credentials/{componentId}
    defaults: { _controller: KeboolaOAuthV2Bundle:Credentials:add }
    methods: [POST]

#keboola_o_auth_list_project_credentials:
    #path: /credentials
    #defaults: { _controller: KeboolaOAuthV2Bundle:Credentials:listAll }
    #methods: [GET]

keboola_o_auth_list_apis:
    path: /manage
    defaults: { _controller: KeboolaOAuthV2Bundle:Manage:list }
    methods: [GET]

keboola_o_auth_api_detail:
    path: /manage/{componentId}
    defaults: { _controller: KeboolaOAuthV2Bundle:Manage:get }
    methods: [GET]

keboola_o_auth_add_api:
    path: /manage
    defaults: { _controller: KeboolaOAuthV2Bundle:Manage:add }
    methods: [POST]

keboola_o_auth_delete_api:
    path: /manage/{componentId}
    defaults: { _controller: KeboolaOAuthV2Bundle:Manage:delete }
    methods: [DELETE]

keboola_o_auth_update_api:
    path: /manage/{componentId}
    defaults: { _controller: KeboolaOAuthV2Bundle:Manage:update }
    methods: [PATCH]

keboola_o_auth_api_auth:
    path: /authorize/{componentId}
    defaults: { _controller: KeboolaOAuthV2Bundle:OAuth:init }
    methods: [POST]

keboola_o_auth_api_auth_test:
    path: /authorize/{componentId}
    defaults: { _controller: KeboolaOAuthV2Bundle:OAuth:testInit }
    methods: [GET]

keboola_o_auth_api_callback:
    path: /authorize/{componentId}/callback
    defaults: { _controller: KeboolaOAuthV2Bundle:OAuth:callback }
    #methods: [GET]

keboola_o_auth_api_detail_decrypt:
    path: /manage/{componentId}/decrypt
    defaults: { _controller: KeboolaOAuthV2Bundle:Manage:getDecrypt }
    methods: [GET]

keboola_o_auth_get_credentials_raw:
    path: /credentials/{componentId}/{id}/raw
    defaults: { _controller: KeboolaOAuthV2Bundle:Credentials:getRaw }
    methods: [GET]
