keboola_o_auth_get_credentials:
    path: /credentials/{componentId}/{id}
    defaults: { _controller: KeboolaOAuthV2Bundle:Credentials:get }
    methods: [GET, POST]

keboola_o_auth_delete_credentials:
    path: /credentials/{componentId}/{id}
    defaults: { _controller: KeboolaOAuthV2Bundle:Credentials:delete }
    methods: [DELETE]

keboola_o_auth_list_credentials:
    path: /credentials/{componentId}
    defaults: { _controller: KeboolaOAuthV2Bundle:Credentials:list }
    methods: [GET]

keboola_o_auth_list_apis:
    path: /manage
    defaults: { _controller: KeboolaOAuthV2Bundle:Manage:list }
    methods: [GET]

keboola_o_auth_api_detail:
    path: /manage/{componentId}
    defaults: { _controller: KeboolaOAuthV2Bundle:Manage:get }
    methods: [GET]

keboola_o_auth_add_api:
    path: /manage
    defaults: { _controller: KeboolaOAuthV2Bundle:Manage:add }
    methods: [POST]

keboola_o_auth_delete_api:
    path: /manage/{componentId}
    defaults: { _controller: KeboolaOAuthV2Bundle:Manage:delete }
    methods: [DELETE]

keboola_o_auth_api_auth:
    path: /authorize/{componentId}
    defaults: { _controller: KeboolaOAuthV2Bundle:OAuth:init }
    methods: [POST]

keboola_o_auth_api_auth_test:
    path: /authorize/{componentId}
    defaults: { _controller: KeboolaOAuthV2Bundle:OAuth:testInit }
    methods: [GET]

keboola_o_auth_api_callback:
    path: /authorize/{componentId}/callback
    defaults: { _controller: KeboolaOAuthV2Bundle:OAuth:callback }
    #methods: [GET]


