services:
    oauth.docker_encryptor:
        class: Keboola\OAuthV2Bundle\Service\DockerEncryptor
        arguments: ["@syrup.storage_api"]

    oauth.session:
        class: Keboola\OAuthV2Bundle\Storage\Session
        arguments: ["@syrup.encryption.base_wrapper", %oauth.providers_db.endpoint%, %oauth.providers_db.user%, %oauth.providers_db.password%, %oauth.providers_db.db%]

