services:
    oauth.docker_encryptor:
        class: Keboola\OAuthV2Bundle\Service\DockerEncryptor
        arguments: ["@syrup.storage_api"]

    oauth.session:
        class: Keboola\OAuthV2Bundle\Storage\Session
        arguments: ["@syrup.encryption.base_wrapper", %database_host%, %database_user%, %database_password%, %database_name%]

    oauth.factory:
        class: Keboola\OAuthV2Bundle\Service\OAuthFactory
